### ISSUE TITLE
dt 4.0.1 Report the LUTs as invalid

### ISSUE THREAD

**Issue by etrigan63** [bastibe/Fujifilm-Auto-Settings-for-Darktable#4]
Trying to apply your styles does not work. DT reports an invalid png file.
Also, the lua script does nothing as well.

**Comment by etrigan63** [comment]
Never mind. I didn't understand your directions. I fixed it now.

**Comment by bastibe** [comment]
If you would like to improve the directions to make it easier for future users, I'd be grateful for a pull request!
