### ISSUE TITLE
script freezes DT on m1 mac, DT4.42

### ISSUE THREAD

**Issue by gase12** [bastibe/Fujifilm-Auto-Settings-for-Darktable#6]
hi. 
the auto script freezes dt immediately after selecting a RAF to import. 
going into the console it prints the exiftools command, it gets all the info needed but halts afterwards.
anyone experienced this? maybe an api change? 
will try to investigate where it stops after line 190.

**Comment by gase12** [comment]
i think it is breaking at applying the style after some logging in the script. 

also found your issue on the dt repo about sg like this: https://github.com/darktable-org/darktable/issues/13985
i guess mac version is not as maintained as linux and the bug is still somewhere present?

**Comment by bastibe** [comment]
What version of Darktable are you using? There was a bug in a prior version of Darktable that crashed when applying a style in a Lua script while in the develop module. This is fixed in the current stable release, however.

**Comment by gase12** [comment]
i was using 4.42 which halts
now the 4.45 dev build seems to work from here: https://discuss.pixls.us/t/current-osx-build/13213/717?page=22

will update this thread if i find anything else
it can be closed for now.
